spring:
  application:
    name: Journal App
  data:
    mongodb:
      host: localhost
      port: 27017
      database: journaldb
#      username: root
#      password: root
      auto-index-creation: true